# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pira < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/piaverous/pira"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/piaverous/pira/releases/download/v0.0.1/pira_0.0.1_Darwin_arm64.tar.gz"
      sha256 "0957835acfacb34260fdd7ada880129df5d34904e4715ca65826c79b951acf7e"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.1/pira_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "632935bd3ee70d04cfa8388dfcd731ee893f0d2baa7099e358bbc7d826066503"

      def install
        bin.install "pira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piaverous/pira/releases/download/v0.0.1/pira_0.0.1_Linux_arm64.tar.gz"
      sha256 "5ad8ab92415300cfeee4881907b2fbe6af37f2e36b59f58b7b5b4d29be545dfb"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.1/pira_0.0.1_Linux_x86_64.tar.gz"
      sha256 "154424827803445f30c13005363109e108e662811d2b5c57980d32289a994626"

      def install
        bin.install "pira"
      end
    end
  end

  test do
    system "#{bin}/pira -version"
  end
end
