# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pira < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/piaverous/pira"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/piaverous/pira/releases/download/v0.0.2/pira_0.0.2_Darwin_arm64.tar.gz"
      sha256 "54bf16563a942e1030b1175bd262a20a0bcbdb270bdea8c9b5954e4e4aa0b848"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.2/pira_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "0095c88f221b34633e279488b26bd6ebea64467f5dd35ea7fa93939128cea2bd"

      def install
        bin.install "pira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piaverous/pira/releases/download/v0.0.2/pira_0.0.2_Linux_arm64.tar.gz"
      sha256 "663ba8ae87df0ce769bc01d62b1779de8bf0106f1ba435eba7687e2ec582c8d6"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.2/pira_0.0.2_Linux_x86_64.tar.gz"
      sha256 "8f14d23a570617c33f676827240403d64836931117bc4de531130a3cff411bfa"

      def install
        bin.install "pira"
      end
    end
  end

  test do
    system "#{bin}/pira -version"
  end
end
