# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pira < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/piaverous/pira"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/piaverous/pira/releases/download/v0.0.3/pira_Darwin_arm64.tar.gz"
      sha256 "d924470d643f13a7c175013c927ac0c2fbbd4f477e9d27c0c7e2ba3f142e5351"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.3/pira_Darwin_x86_64.tar.gz"
      sha256 "cc94e6c5d1a4f86387965570ccbdd53f2b17cb5100df6069112f69e5cd06d144"

      def install
        bin.install "pira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piaverous/pira/releases/download/v0.0.3/pira_Linux_arm64.tar.gz"
      sha256 "8e91b9450b621f8ee50182625c1c7f03db2b1e70fb1ccb6e5b3dafb664b748e3"

      def install
        bin.install "pira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pira/releases/download/v0.0.3/pira_Linux_x86_64.tar.gz"
      sha256 "413c721b9657f85dcfaa150608688f7e61a1b46d5e423d419769dfb88353ace0"

      def install
        bin.install "pira"
      end
    end
  end

  test do
    system "#{bin}/pira -version"
  end
end
