# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pokta < Formula
  desc "Interact with Jira from your terminal"
  homepage "https://github.com/piaverous/pokta"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/piaverous/pokta/releases/download/v0.0.1/pokta_Darwin_arm64.tar.gz"
      sha256 "18bcabefc9c1cb05481290346f8f00e5c9a0105073fd958f49fa4e5124fd72ac"

      def install
        bin.install "pokta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pokta/releases/download/v0.0.1/pokta_Darwin_x86_64.tar.gz"
      sha256 "242f9c1f68bf861e742e8a149d76b1fd934f9fec7ddce46dd84bb0fbbf6b91ea"

      def install
        bin.install "pokta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piaverous/pokta/releases/download/v0.0.1/pokta_Linux_arm64.tar.gz"
      sha256 "f215f8a93df9b7d6fbfe35de92cf91318969582237194e656a41145f85b520a4"

      def install
        bin.install "pokta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piaverous/pokta/releases/download/v0.0.1/pokta_Linux_x86_64.tar.gz"
      sha256 "510417fa8d4263f93a1568a4b01c9298797b42faf5e8e6a66f2c1f2fed17d5e4"

      def install
        bin.install "pokta"
      end
    end
  end

  test do
    system "#{bin}/pokta -version"
  end
end
